### ISSUE TITLE
Bug: Drag and drop redirects to direct image link on Firefox

### ISSUE THREAD

**Issue by camdendotlol** [camdendotlol/topstersorg#12]
On Firefox, when you drag an item to the chart, the browser redirects to the image.

I remember trying to fix this back in December and I couldn't figure out what was causing it.

**Comment by sirsnowy7** [comment]
bump

**Comment by camdendotlol** [comment]
@sirsnowy7 Have you updated to Firefox 105? It came out September 20 and seems to have fixed this issue on my end.

**Comment by camdendotlol** [comment]
Closing, as this seems to have been fixed on Firefox's end some time ago.
